---
- hosts: myWebservers
  become: yes
  gather_facts: yes
  tasks:
  - name: I want to install websever on ubuntu node
    apt:
     name: "{{mywebpackonUbuntu}}"
     state: present
    when: ansible_os_family=="Debian"
  

  - name: I want to start webserver on ubuntu node
    service:
     name: "{{mywebpackonUbuntu}}"
     state: started
    when: ansible_os_family=="Debian"

  - name: I want to install webserver on Redhat
    dnf:
     name: "{{mywebpackonRedHat}}"
     state: present
    when: ansible_os_family=="RedHat"
  - name: I want to start webserver on Redhat
    service:
     name: "{{mywebpackonRedHat}}"
     state: started
    when: ansible_os_family=="RedHat"     
